export const PHONE_VERIFICATION = 'PHONE_VERIFICATION';
export const PHONE_VERIFICATION_FINISH = 'PHONE_VERIFICATION_FINISH';
export const EMAIL_VERIFICATION = 'EMAIL_VERIFICATION';
export const EMAIL_VERIFICATION_STATUS = 'EMAIL_VERIFICATION_STATUS';
export const NEW_USER = 'NEW_USER';
export const USER_LOGIN = 'USER_LOGIN';
export const LOADING = 'LOADING';
export const ERROR = 'ERROR';
